
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Login
{

using System;
    using System.Collections.Generic;
    
public partial class Employee
{

    public int Reg { get; set; }

    public string CompanyCodee { get; set; }

    public string PayrollCodee { get; set; }

    public string Statement { get; set; }

    public string Personel { get; set; }

    public string yymm { get; set; }

}

}
